version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: hi-all-min-laravel-app
    container_name: hi_all_min_laravel_app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    ports:
      - "8080:80"
    networks:
      - hi_all_min_network

  mysql:
    image: mysql:8.0
    container_name: hi_all_min_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: laravel_password
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - hi_all_min_network

networks:
  hi_all_min_network:
    driver: bridge

volumes:
  mysql_data:
    driver: local

